Added Examples for Various Text & Layout Modifiers
barbaramartina/swiftuicatalog pull request #45
Opened 2024-06-15 10:46 UTC by meetAhmed

Hi **Barbara**, thank you for this awesome repo.

> This pull request includes the following additions  and updates:

Examples Added:
- ActionSheet
- Confirmation dialog
- ZIndex
- Layout priority
- Offset
- Fixed size view

Updates:
- ContentView to reflect the new examples.
- Added a few text modifiers for enhanced text styling.

2024-07-01 07:48 UTC, barbaramartina commented
Hi @meetAhmed, I was on holidays for some weeks, I will review your contribution. Thanks for adding it.

2024-07-01 08:48 UTC, barbaramartina requested changes
thanks for your contributions, I have reviewed it and most of the examples are already in (ActionSheet, ZIndex, Layout priority, Offset, Fixed size view). For modifiers we do not create new views, there is a section about how to contribute in the readme, I moved it up in the text, so it is more visible.

The examples for text selection are great, could you adjust the PR to leave this contribution please? I would like to merge that part.

Confirmation Dialog, is a custom view, not a standard component so I prefer to not include it unless it is made reusable and customizable, as the other views in the reusable views section.

2024-07-02 06:55 UTC, meetAhmed commented on SwiftUICatalog/Views/Sections/View Layouts/OffsetView.swift
> +import SwiftUI
OffsetView file removed.

2024-07-02 06:55 UTC, meetAhmed commented on SwiftUICatalog/Views/Sections/View Layouts/ZIndexView.swift
> +struct ZIndexView: View, Comparable {
ZIndexView file removed.

2024-07-02 06:56 UTC, meetAhmed commented on SwiftUICatalog/Views/Sections/View Layouts/FixedSizeExampleView.swift
> +struct FixedSizeExampleView: View, Comparable {
FixedSizeExampleView file removed.

2024-07-02 06:56 UTC, meetAhmed commented on SwiftUICatalog/Views/Sections/View Layouts/ActionSheetView.swift
> +private extension ActionSheetView {
ActionSheetView file removed.

2024-07-02 06:58 UTC, meetAhmed commented
Hi @barbaramartina, I have removed duplicated code. Please take a look when you get some time. Thank you.

2024-07-06 11:32 UTC, barbaramartina approved these changes

2024-07-06 11:32 UTC, barbaramartina commented
Thanks for your contribution, I am incorporating it today to the main code. Have a good weekend.

2024-07-06 11:33 UTC, merged